name: Most used (with details)
on:
  pull_request_target:
    branches:
      - main
      - latest
      - examples

jobs:
  notice:
    name: Notice for automated branches
    runs-on: ubuntu-latest
    steps:
      - name: Comment on pull request
        uses: actions/github-script@v6
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
 

